# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [27]:
import pandas as pd
# Your code here
df=pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.drop_duplicates(inplace=True)
df=df.dropna(how='all')
df.columns=["Customer","State","Gender","Education","Customer Lifetime Value", "Income","Monthly Premium Auto","Number of Open Complaints","Policy Type","Vehicle Class","Total Claim Amount"]
#df.rename(columns= {'passenger_id': 'PassengerId'}, inplace=True)
df.columns=[col.replace(" ","_") for col in df.columns]
df

,Customer,State,Gender,Education,Customer_Lifetime_Value,Income,Monthly_Premium_Auto,Number_of_Open_Complaints,Policy_Type,Vehicle_Class,Total_Claim_Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1/1/00,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,1/2/00,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11%,79487.0,114.0,1/0/00,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [29]:

df["Gender"]=df["Gender"].str.strip().str.title().replace({"Femal":"F","Male":"M","Female":"F"})
df["Gender"].unique()

C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1184480552.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"]=df["Gender"].str.strip().str.title().replace({"Femal":"F","Male":"M","Female":"F"})

array([nan, 'F', 'M'], dtype=object)

In [30]:

df["Vehicle_Class"]=df["Vehicle_Class"].replace({"Sports Car":"Luxury","Luxury SUV":"Luxury","Luxury Car":"Luxury"})
df["Vehicle_Class"].unique()

C:\Users\claud\AppData\Local\Temp\ipykernel_22304\2494526773.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Vehicle_Class"]=df["Vehicle_Class"].replace({"Sports Car":"Luxury","Luxury SUV":"Luxury","Luxury Car":"Luxury"})

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury'], dtype=object)

In [31]:
df["Education"]=df["Education"].replace("Bachelors","Bachelor")
df["Education"].unique()

C:\Users\claud\AppData\Local\Temp\ipykernel_22304\3609773597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Education"]=df["Education"].replace("Bachelors","Bachelor")

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor'],
      dtype=object)

In [32]:
df["State"].unique()
df["State"].replace({"AZ":"Arizona","WA":"Washington"},inplace=True)
df["State"].unique()

C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1731171339.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["State"].replace({"AZ":"Arizona","WA":"Washington"},inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1731171339.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["State"].replace({"AZ":"Arizona","WA":"Washington"},inplace=True)

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali'],
      dtype=object)

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [33]:
df["Customer_Lifetime_Value"] = (
    df["Customer_Lifetime_Value"].replace({"%": ""}, regex=True).astype(float).round(2)
)

C:\Users\claud\AppData\Local\Temp\ipykernel_22304\54724908.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Customer_Lifetime_Value"] = (

In [34]:
df["Number_of_Open_Complaints"].replace({"1/0/00":0,"1/2/00":2,"1/1/00":1,"1/3/00":3,"1/4/00":4,"1/5/00":5},inplace=True)
df["Number_of_Open_Complaints"].unique()

C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1621494075.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Number_of_Open_Complaints"].replace({"1/0/00":0,"1/2/00":2,"1/1/00":1,"1/3/00":3,"1/4/00":4,"1/5/00":5},inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1621494075.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Number_of_Open_Complaints"].replace({"1/0/00":0,"1/2/00":2,"1/1/00":1,"1/3/00":3,"1/4/00":4,"1/5/00":5},inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1621494075.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Number_of_Open_Complaints"].replace({"1/0/00":0,"1/2/00":2,"1/1/00":1,"1/3/00":3,"1/4/00":4,"1/5/00":5},inplace=True)

array([0, 2, 1, 3, 5, 4])

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [35]:
df.isnull().sum()
df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)
df["Customer_Lifetime_Value"].fillna(method="ffill",inplace=True)
df["Customer_Lifetime_Value"].fillna(method="bfill",inplace=True)
df.isnull().sum()

C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"].fillna(df["Gender"].mode()[0],inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Customer_Lifetime_Value"].fillna(method="ffill",inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Customer_Lifetime_Value"].fillna(method="ffill",inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Customer_Lifetime_Value"].fillna(method="ffill",inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Customer_Lifetime_Value"].fillna(method="bfill",inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Customer_Lifetime_Value"].fillna(method="bfill",inplace=True)
C:\Users\claud\AppData\Local\Temp\ipykernel_22304\1012397122.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Customer_Lifetime_Value"].fillna(method="bfill",inplace=True)

Customer                     0
State                        0
Gender                       0
Education                    0
Customer_Lifetime_Value      0
Income                       0
Monthly_Premium_Auto         0
Number_of_Open_Complaints    0
Policy_Type                  0
Vehicle_Class                0
Total_Claim_Amount           0
dtype: int64

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [36]:
df.duplicated().sum()

np.int64(0)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [37]:
def remove_duplicates(df):
    df.drop_duplicates(inplace=True)
    df.dropna(how="all",inplace=True)
    return df
def format_columns(df):
    #Rename columns and standardize column names
    df.columns = [
        "Customer",
        "State",
        "Gender",
        "Education",
        "Customer Lifetime Value",
        "Income",
        "Monthly Premium Auto",
        "Number of Open Complaints",
        "Policy Type",
        "Vehicle Class",
        "Total Claim Amount",
    ]
    # Replace spaces with underscores
    df.columns = [col.replace(" ", "_") for col in df.columns]
    return df
def clean_categorical_values(df):
    """Fix inconsistent categorical values."""
    df["Gender"] = (
        df["Gender"].astype(str).str.strip().str.title().replace({"Femal": "F", "Male": "M", "Female": "F"})
    )
    df["Vehicle_Class"] = df["Vehicle_Class"].replace({"Sports Car": "Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"})
    df["Education"] = df["Education"].replace("Bachelors", "Bachelor")
    return df
def format_numeric_values(df):
   #Convert numeric-like columns to float and clean symbols.
    # Customer Lifetime Value
    df["Customer_Lifetime_Value"] = (
        df["Customer_Lifetime_Value"].replace({"%": ""}, regex=True).astype(float)
    )

    # Number of Open Complaints
    df["Number_of_Open_Complaints"].replace(
        {
            "1/0/00": 0,
            "1/1/00": 1,
            "1/2/00": 2,
            "1/3/00": 3,
            "1/4/00": 4,
            "1/5/00": 5,
        },
        inplace=True,
    )

    return df
def fill_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """Impute missing data using mode and forward/backward fill."""
    df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)
    df["Customer_Lifetime_Value"].fillna(method="ffill", inplace=True)
    df["Customer_Lifetime_Value"].fillna(method="bfill", inplace=True)
    return df

def clean_and_format_data(df):
   
    df = remove_duplicates(df)
    df = format_columns(df)
    df = clean_categorical_values(df)
    df = format_numeric_values(df)
    df = fill_missing_values(df)
    return df

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [39]:
df[["Total_Claim_Amount","Customer_Lifetime_Value"]].describe()

       Total_Claim_Amount  Customer_Lifetime_Value
count         1071.000000             1.071000e+03
mean           404.986909             7.934125e+05
std            293.027260             6.426141e+05
min              0.382107             2.004351e+05
25%            202.157702             4.048535e+05
50%            354.729129             5.884309e+05
75%            532.800000             8.945210e+05
max           2893.239678             5.816655e+06

In [ ]:
claim_25=df["Customer_Lifetime_Value"].quantile(0.25)
claim_25

np.float64(404853.45999999996)

In [42]:
claim_75=df["Total_Claim_Amount"].quantile(0.75)
claim_75

np.float64(532.8)

In [45]:
filtered_df = df[(df["Total_Claim_Amount"] > claim_75) &(df["Customer_Lifetime_Value"] < claim_25)]
filtered_df

,Customer,State,Gender,Education,Customer_Lifetime_Value,Income,Monthly_Premium_Auto,Number_of_Open_Complaints,Policy_Type,Vehicle_Class,Total_Claim_Amount
17,OE15005,Cali,F,College,394524.16,28855.0,101.0,0,Personal Auto,SUV,647.442031
23,TZ98966,Nevada,F,Bachelor,245019.10,0.0,73.0,3,Corporate Auto,Four-Door Car,554.376763
26,US89481,California,F,Bachelor,394637.21,0.0,111.0,0,Personal Auto,Four-Door Car,799.200000
38,CM61827,Oregon,F,Bachelor,309003.41,0.0,90.0,0,Personal Auto,Two-Door Car,648.000000
42,IL19217,California,F,Bachelor,393900.64,60021.0,99.0,0,Personal Auto,Four-Door Car,882.871945
62,FG63582,Oregon,F,Bachelor,333976.49,0.0,94.0,0,Personal Auto,Two-Door Car,863.327324
135,MS41162,Arizona,F,High School or Below,402296.35,0.0,117.0,0,Personal Auto,SUV,975.107098
140,DS81757,Oregon,M,College,247012.12,0.0,74.0,0,Personal Auto,Two-Door Car,721.242206
158,KA61892,Arizona,M,College,387364.70,28142.0,105.0,0,Personal Auto,Luxury,701.708239
160,ND87334,California,M,High School or Below,228759.69,0.0,63.0,0,Corporate Auto,Two-Door Car,679.368378
170,TS19868,California,M,College,241313.97,27501.0,63.0,0,Personal Auto,Four-Door Car,542.319401
184,AB13432,California,M,Bachelor,373583.81,0.0,110.0,0,Personal Auto,SUV,792.000000
204,FL34139,California,M,High School or Below,368811.09,0.0,63.0,3,Personal Auto,Four-Door Car,669.682001
250,IA63417,Arizona,F,High School or Below,400151.91,19782.0,108.0,0,Personal Auto,Two-Door Car,773.470977
269,VZ51506,Arizona,F,High School or Below,359531.29,0.0,103.0,0,Corporate Auto,Luxury,741.600000
279,OH60605,Oregon,F,High School or Below,365253.24,39679.0,92.0,0,Personal Auto,Two-Door Car,641.388616
304,RR77985,Oregon,F,Bachelor,288774.23,0.0,80.0,0,Personal Auto,Four-Door Car,676.944023
388,JF36291,California,M,College,387364.70,28142.0,105.0,0,Personal Auto,Luxury,701.708239
415,ZF84449,Oregon,F,College,372672.80,0.0,112.0,1,Special Auto,Luxury,806.400000
448,NL93182,Nevada,M,Bachelor,254945.00,0.0,78.0,0,Corporate Auto,Four-Door Car,845.654042
450,WE68644,Oregon,F,Bachelor,380392.18,20325.0,100.0,0,Personal Auto,Luxury,668.293970
467,AU96286,Oregon,F,Bachelor,316765.84,0.0,92.0,0,Corporate Auto,Four-Door Car,662.400000
486,FY51713,Arizona,F,Bachelor,357076.05,56168.0,88.0,0,Personal Auto,Four-Door Car,614.675906
500,XN11823,Nevada,F,Bachelor,376446.51,92600.0,94.0,0,Corporate Auto,Two-Door Car,842.437850
502,PX17116,Nevada,M,College,362345.42,0.0,111.0,2,Corporate Auto,SUV,1171.931170
565,XS12556,California,F,College,368309.99,0.0,101.0,0,Corporate Auto,Luxury,564.466556
590,UK41984,Arizona,F,Doctor,383960.61,0.0,112.0,2,Personal Auto,SUV,537.600000
593,ZK21724,Oregon,F,High School or Below,401654.20,0.0,111.0,0,Personal Auto,SUV,799.200000
638,DM95829,California,M,College,252395.96,16244.0,68.0,0,Personal Auto,Two-Door Car,623.223617
645,JA41698,Nevada,M,Bachelor,309953.80,0.0,102.0,5,Corporate Auto,SUV,862.762957
669,ED50963,California,F,High School or Below,268886.40,32808.0,68.0,1,Personal Auto,Four-Door Car,541.695658
709,NZ15548,Oregon,M,Bachelor,402381.44,41833.0,103.0,0,Personal Auto,Four-Door Car,643.826716
788,TE13577,Oregon,F,College,231973.59,0.0,64.0,0,Personal Auto,Four-Door Car,632.715382
853,TV25678,Washington,M,College,354090.43,0.0,101.0,0,Personal Auto,SUV,727.200000
891,KJ87930,Cali,F,Bachelor,388650.48,0.0,112.0,0,Corporate Auto,SUV,1185.988301
908,XM72420,Arizona,F,High School or Below,391936.67,66676.0,97.0,0,Personal Auto,Four-Door Car,558.099357
949,TD10493,Oregon,F,High School or Below,289873.27,0.0,96.0,4,Personal Auto,Four-Door Car,691.200000
1019,OT52034,Cali,M,Bachelor,386477.68,24204.0,99.0,1,Personal Auto,Four-Door Car,707.303416
1022,UI73201,Cali,M,College,366737.50,62375.0,92.0,0,Personal Auto,Two-Door Car,618.630955
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000

In [46]:
summary_stats = filtered_df[["Total_Claim_Amount", "Customer_Lifetime_Value"]].describe()
summary_stats

       Total_Claim_Amount  Customer_Lifetime_Value
count           40.000000                40.000000
mean           723.776577            341577.910000
std            149.280606             56921.472027
min            537.600000            228759.690000
25%            633.378846            304220.875000
50%            685.284189            365995.370000
75%            799.200000            387364.700000
max           1185.988301            402381.440000